/***********************************************
* GENERATED BY ZEBBLE
***********************************************/

using Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Zebble;

#region UI.Pages.Page1
namespace UI.Pages
{
    public partial class Page1 : Templates.Default
    {
        public Modules.ContactsList ContactsList;

        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();
            Data["TopMenu"] = "MainMenu";
            Title = "Page 1";

            Body.Add(ContactsList = new Modules.ContactsList { Id = "ContactsList" });

            return Task.CompletedTask;
        }
    }
}
#endregion

namespace UI
{
    partial class StartUp
    {
        // Hashed content of all resources
        public override string GetResourcesVersion() => "wGQYblglWZII4j4yadZWt0pRe4";
    }
}